# Generated by Django 5.1.5 on 2025-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='observSesiones',
            field=models.TextField(blank=True, default='Estado inicia como registrado'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='sesiones',
            field=models.IntegerField(default=6),
        ),
    ]
