# Generated by Django 5.1.5 on 2025-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_servicios_observsesiones_servicios_sesiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='ServicioNombre',
            field=models.CharField(choices=[('Fi', 'Finanzas'), ('Gp', 'Procesos'), ('BI', 'Inteligencia de Negocio')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='observSesiones',
            field=models.TextField(blank=True, default='Se realizan 6 sesiones'),
        ),
    ]
