# Generated by Django 5.1.5 on 2025-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_servicios_servicionombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
